name: tests unitaires

on:
  push:
  pull_request:

jobs:
  test1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install pytest
        run: python -m pip install --upgrade pip pytest

      - name: Run tests
        run: python -m pytest TP1/test.py -q
        
